// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvuYbMIZCcM6MvZLyg6mlbIDo4Nc3oG8',
    appId: '1:873539268433:web:a2e6578b2572d7d0cded70',
    messagingSenderId: '873539268433',
    projectId: 'pet-accounting',
    authDomain: 'pet-accounting.firebaseapp.com',
    storageBucket: 'pet-accounting.firebasestorage.app',
    measurementId: 'G-JL2KWZQ7JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_3ts_kuoy-k7NTYBZi0PKxKA_ve-BrlU',
    appId: '1:873539268433:android:9573229fd90b1764cded70',
    messagingSenderId: '873539268433',
    projectId: 'pet-accounting',
    storageBucket: 'pet-accounting.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpPD4VZMIAyl4ALnVpLkGYCeMCGeOfRFY',
    appId: '1:873539268433:ios:1096cd213256c006cded70',
    messagingSenderId: '873539268433',
    projectId: 'pet-accounting',
    storageBucket: 'pet-accounting.firebasestorage.app',
    androidClientId: '873539268433-mkvh5s37bqsupq2b11vs026hi0hovpeb.apps.googleusercontent.com',
    iosClientId: '873539268433-n82dv4bb2sqf7ebp3rvk3o5gr91s8hko.apps.googleusercontent.com',
    iosBundleId: 'com.example.userInterface',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpPD4VZMIAyl4ALnVpLkGYCeMCGeOfRFY',
    appId: '1:873539268433:ios:1096cd213256c006cded70',
    messagingSenderId: '873539268433',
    projectId: 'pet-accounting',
    storageBucket: 'pet-accounting.firebasestorage.app',
    androidClientId: '873539268433-mkvh5s37bqsupq2b11vs026hi0hovpeb.apps.googleusercontent.com',
    iosClientId: '873539268433-n82dv4bb2sqf7ebp3rvk3o5gr91s8hko.apps.googleusercontent.com',
    iosBundleId: 'com.example.userInterface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGvuYbMIZCcM6MvZLyg6mlbIDo4Nc3oG8',
    appId: '1:873539268433:web:e5c89450557a546ecded70',
    messagingSenderId: '873539268433',
    projectId: 'pet-accounting',
    authDomain: 'pet-accounting.firebaseapp.com',
    storageBucket: 'pet-accounting.firebasestorage.app',
    measurementId: 'G-03K618GHWF',
  );
}